const $ = id => document.getElementById(id);
let boot = null, searchTimer = null;
const API_URL = (window.ARYA_CONFIG && window.ARYA_CONFIG.API_URL || '').trim();
const money = n => '₹' + Number(n || 0).toLocaleString('en-IN', {maximumFractionDigits: 2});
const esc = s => String(s ?? '').replace(/[&<>'"]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));

function api(action,payload={}){return new Promise((resolve,reject)=>{if(!API_URL||API_URL.includes('PASTE_')) return reject(new Error('API URL is not configured in config.js.'));const cb='aryaCb_'+Date.now()+'_'+Math.random().toString(36).slice(2);const s=document.createElement('script');const timer=setTimeout(()=>finish(new Error('Connection timed out. Please check internet and Apps Script deployment.')),25000);function finish(err,value){clearTimeout(timer);delete window[cb];s.remove();err?reject(err):resolve(value)}window[cb]=res=>res&&res.ok?finish(null,res.data):finish(new Error((res&&res.error)||'Request failed'));s.onerror=()=>finish(new Error('Could not reach the Google Sheets backend.'));const q=new URLSearchParams({action,callback:cb,payload:JSON.stringify(payload)});s.src=API_URL+'?'+q.toString();document.head.appendChild(s)})}
function toast(msg,error=false){const t=$('toast');t.textContent=msg;t.className='toast show'+(error?' error':'');setTimeout(()=>t.className='toast',3000)}
function busy(on){$('loading').classList.toggle('show',on)}
function go(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('[data-nav]').forEach(b=>b.classList.toggle('active',b.dataset.nav===id));scrollTo({top:0,behavior:'smooth'});if(id==='members')loadMembers();if(id==='subscription')loadStatus();if(id==='ledger')loadLedger()}
function fyOptions(current){const start=Number(current.slice(0,4));return [start-1,start,start+1,start+2].map(y=>`${y}-${String(y+1).slice(-2)}`)}
function fillSelect(id,items){$(id).innerHTML=items.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}

async function startApp(){busy(true);try{boot=await api('bootstrap');setupFromBoot();}catch(e){toast(e.message,true)}finally{busy(false)}}
function setupFromBoot(){['inDate','exDate','subDate'].forEach(id=>$(id).value=boot.today);fillSelect('inCategory',boot.incomeCategories);fillSelect('exCategory',boot.expenseCategories);['inPayment','exPayment','subPayment'].forEach(id=>fillSelect(id,boot.paymentTypes));const fys=fyOptions(boot.financialYear);['homeFY','subFY','ledgerFY'].forEach(id=>fillSelect(id,fys));$('homeFY').value=$('subFY').value=$('ledgerFY').value=boot.financialYear;renderDashboard(boot.dashboard)}
function wire(){
 document.querySelectorAll('[data-nav]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.nav)));document.querySelectorAll('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
 $('inCategory').addEventListener('change',()=>toggleOther('in'));$('exCategory').addEventListener('change',()=>toggleOther('ex'));['in','ex','sub'].forEach(p=>$(p+'Payment').addEventListener('change',()=>togglePayment(p)));
 $('saveIncome').addEventListener('click',saveIncome);$('saveExpense').addEventListener('click',saveExpense);$('saveMember').addEventListener('click',saveMember);$('saveSubscription').addEventListener('click',saveSubscription);
 $('memberSearch').addEventListener('input',debounce(loadMembers));$('subMemberSearch').addEventListener('input',debounce(searchSubMembers));$('statusSearch').addEventListener('input',debounce(loadStatus));$('subFY').addEventListener('change',loadStatus);
 $('homeScope').addEventListener('change',()=>{const s=$('homeScope').value;$('homePeriod').style.display=s==='month'?'block':'none';$('homeFY').style.display=s==='fy'?'block':'none';refreshDashboard()});$('homeFY').addEventListener('change',refreshDashboard);$('homePeriod').addEventListener('change',refreshDashboard);
 $('ledgerScope').addEventListener('change',()=>{$('ledgerMonth').style.display=$('ledgerScope').value==='month'?'block':'none';$('ledgerFY').style.display=$('ledgerScope').value==='fy'?'block':'none'});$('refreshLedger').addEventListener('click',loadLedger);
}
function debounce(fn){return()=>{clearTimeout(searchTimer);searchTimer=setTimeout(fn,300)}}
function toggleOther(p){$(p+'OtherWrap').style.display=$(p+'Category').value==='Other'?'block':'none'}
function togglePayment(p){const v=$(p+'Payment').value;$(p+'PaymentDetailWrap').style.display=(v==='Cheque'||v==='Other'||v==='Bank Transfer')?'block':'none'}
async function saveIncome(){const description=$('inCategory').value==='Other'?$('inOther').value:$('inCategory').value;await save('saveIncome','addIncome',{date:$('inDate').value,receiptNo:$('inReceipt').value,amount:$('inAmount').value,description,paymentType:$('inPayment').value,paymentDetail:$('inPaymentDetail').value},()=>{$('inReceipt').value='';$('inAmount').value='';$('inOther').value='';refreshDashboard()})}
async function saveExpense(){const description=$('exCategory').value==='Other'?$('exOther').value:$('exCategory').value;await save('saveExpense','addExpense',{date:$('exDate').value,receiptNo:$('exVoucher').value,amount:$('exAmount').value,description,vendor:$('exVendor').value,paymentType:$('exPayment').value,paymentDetail:$('exPaymentDetail').value},()=>{$('exVoucher').value='';$('exAmount').value='';$('exVendor').value='';$('exOther').value='';refreshDashboard()})}
async function saveMember(){await save('saveMember','addMember',{name:$('newName').value,address:$('newAddress').value,mobile:$('newMobile').value},()=>{$('newName').value=$('newAddress').value=$('newMobile').value='';loadMembers();refreshDashboard()})}
async function saveSubscription(){await save('saveSubscription','addSubscription',{memberName:$('subMemberName').value||$('subMemberSearch').value,address:$('subAddress').value,date:$('subDate').value,financialYear:$('subFY').value,receiptNo:$('subReceipt').value,amount:$('subAmount').value,paymentType:$('subPayment').value,paymentDetail:$('subPaymentDetail').value},()=>{$('subReceipt').value='';$('subAmount').value='';$('subMemberName').value='';$('subAddress').value='';$('subMemberSearch').value='';$('chosenMember').style.display='none';$('subMemberResults').innerHTML='';loadStatus();refreshDashboard()})}
async function save(btnId,method,payload,after){const b=$(btnId);b.disabled=true;busy(true);try{const r=await api(method,payload);toast(r.message||'Saved');after&&after()}catch(e){toast(e.message,true)}finally{b.disabled=false;busy(false)}}
async function refreshDashboard(){try{renderDashboard(await api('dashboard',{scope:$('homeScope').value,financialYear:$('homeFY').value,month:$('homePeriod').value}))}catch(e){toast(e.message,true)}}
function renderDashboard(d){$('statIncome').textContent=money(d.totalIncome);$('statExpense').textContent=money(d.expenses);$('statBalance').textContent=money(d.balance);$('statBalance').className='value '+(d.balance>=0?'positive':'negative');$('statMembers').textContent=d.memberCount;$('subscriptionStat').textContent='Annual subscriptions: '+money(d.subscriptions);$('recentList').innerHTML=d.recent.length?d.recent.map(txHtml).join(''):'<div class="empty">No entries in this period.</div>'}
function txHtml(r){const title=r.type==='Subscription'?(r.member||'Annual Subscription'):r.description;return `<div class="item"><div class="item-top"><div><strong>${esc(title)}</strong><div class="meta">${esc(r.date)} • ${esc(r.type)}${r.reference?' • '+esc(r.reference):''}</div></div><div class="amount ${r.type==='Expense'?'negative':'positive'}">${r.type==='Expense'?'-':'+'}${money(r.amount)}</div></div>${r.payment?`<div class="meta">${esc(r.payment)}</div>`:''}</div>`}
async function loadMembers(){try{const rows=await api('members',{query:$('memberSearch').value});$('memberList').innerHTML=rows.length?rows.map(m=>`<div class="item"><strong>${esc(m.name)}</strong><div class="meta">${esc(m.address||'No address')}${m.mobile?' • '+esc(m.mobile):''}</div></div>`).join(''):'<div class="empty">No member found.</div>'}catch(e){toast(e.message,true)}}
async function searchSubMembers(){const q=$('subMemberSearch').value;if(q.length<2){$('subMemberResults').innerHTML='';return}try{const rows=await api('members',{query:q});$('subMemberResults').innerHTML=rows.slice(0,12).map((m,i)=>`<button type="button" class="member-choice" data-i="${i}"><strong>${esc(m.name)}</strong><span class="meta">${esc(m.address||'')}</span></button>`).join('');document.querySelectorAll('.member-choice').forEach(b=>b.addEventListener('click',()=>chooseMember(rows[Number(b.dataset.i)])))}catch(e){toast(e.message,true)}}
function chooseMember(m){$('subMemberSearch').value=m.name;$('subMemberName').value=m.name;$('subAddress').value=m.address||'';$('subMemberResults').innerHTML='';$('chosenMember').style.display='block';$('chosenMember').innerHTML=`Selected: <strong>${esc(m.name)}</strong>${m.address?'<br>'+esc(m.address):''}`}
async function loadStatus(){try{const rows=await api('subscriptionStatus',{financialYear:$('subFY').value,query:$('statusSearch').value});$('statusList').innerHTML=rows.length?rows.map(m=>`<div class="item"><div class="item-top"><div><strong>${esc(m.name)}</strong><div class="meta">${esc(m.address||'')}</div></div><span class="badge ${m.paid>0?'paid':'unpaid'}">${m.paid>0?'Paid '+money(m.paid):'Not recorded'}</span></div></div>`).join(''):'<div class="empty">No member found.</div>'}catch(e){toast(e.message,true)}}
async function loadLedger(){busy(true);try{const rows=await api('ledger',{scope:$('ledgerScope').value,financialYear:$('ledgerFY').value,month:$('ledgerMonth').value,query:$('ledgerSearch').value});$('ledgerList').innerHTML=rows.length?rows.map(txHtml).join(''):'<div class="empty">No ledger entries found.</div>'}catch(e){toast(e.message,true)}finally{busy(false)}}
if('serviceWorker' in navigator){window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}))}
wire();startApp();
